### ISSUE TITLE
repository: panic: runtime error: unsafe pointer conversion

### ISSUE THREAD

**Issue by TimSatke** [gojisvm/gojis#84]
In Go1.14, `-d=checkptr` is enabled with `-race` by default, which results in a test failure.
```
--- FAIL: TestSimple (0.00s)
panic: runtime error: unsafe pointer conversion [recovered]
	panic: runtime error: unsafe pointer conversion
goroutine 7 [running]:
testing.tRunner.func1(0xc0000aa6c0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:916 +0xaeb
panic(0x8dce40, 0xc00000e560)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:967 +0x396
github.com/gojisvm/gojis/tools/snapshot.bytesAt(...)
	/home/travis/gopath/src/github.com/gojisvm/gojis/tools/snapshot/snapshot.go:191
github.com/gojisvm/gojis/tools/snapshot.toInternalNested(0xc000031070, 0x9a3640, 0x8b4ba0, 0x9a3640)
	/home/travis/gopath/src/github.com/gojisvm/gojis/tools/snapshot/snapshot.go:175 +0xdc
github.com/gojisvm/gojis/tools/snapshot.storeInternal(0x885540, 0xc000031070, 0xc0000a82a0)
	/home/travis/gopath/src/github.com/gojisvm/gojis/tools/snapshot/snapshot.go:167 +0x125
github.com/gojisvm/gojis/tools/snapshot.storeToCapnp(0x885540, 0xc000031070, 0xc0000a82a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8, 0x28)
	/home/travis/gopath/src/github.com/gojisvm/gojis/tools/snapshot/snapshot.go:109 +0x159
github.com/gojisvm/gojis/tools/snapshot.Store(0x997660, 0xc000013440, 0x885540, 0xc000031070, 0x5dc95758, 0xc0000406c0)
	/home/travis/gopath/src/github.com/gojisvm/gojis/tools/snapshot/snapshot.go:78 +0x1c2
github.com/gojisvm/gojis/tools/snapshot_test.TestSimple(0xc0000aa6c0)
	/home/travis/gopath/src/github.com/gojisvm/gojis/tools/snapshot/snapshot_test.go:38 +0x116
testing.tRunner(0xc0000aa6c0, 0x925f00)
	/home/travis/.gimme/versions/go/src/testing/testing.go:954 +0x1ec
created by testing.(*T).Run
	/home/travis/.gimme/versions/go/src/testing/testing.go:1005 +0x661
```

See golang/go#34964

**Comment by TimSatke** [comment]
Fixed as of 6ed8f5c0eaa2647ada26b50482dcf53b707992c1
